### ISSUE TITLE
First time contributors are welcomed.

### ISSUE THREAD

**Issue by thedevelopersanjeev** [thedevelopersanjeev/Learn-Git#66]

**Comment by Mart-Bogdan** [comment]
This is cheating)

**Comment by thedevelopersanjeev** [comment]
Why @Mart-Bogdan  ?

**Comment by CodeDraken** [comment]
The point is to get people to contribute to open source. This only takes away from that.

There's already a tutorial on the Hacktoberfest site on how to make a PR.

**Comment by thedevelopersanjeev** [comment]
So, Should I remove it from here @CodeDraken  ?

**Comment by CodeDraken** [comment]
I would, but that's up to you.

**Comment by damiansire** [comment]
Thanks, i think I did it well

**Comment by Mart-Bogdan** [comment]
not again, I thought it was over last year!
